# Generated by Django 4.1.7 on 2023-03-23 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profilePic', models.ImageField(blank=True, upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('rate', models.FloatField(blank=True)),
                ('completedJobs', models.IntegerField(blank=True)),
                ('joinedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('skills', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('wallet', models.FloatField(blank=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profilePic', models.ImageField(blank=True, upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField(blank=True)),
                ('completedProjects', models.TextField(blank=True)),
                ('availableProjects', models.TextField(blank=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
