# Generated by Django 4.1.7 on 2023-04-11 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profiles/')),
                ('about', models.TextField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profiles/')),
                ('rate', models.FloatField(blank=True, null=True)),
                ('joinedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('skills', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('full stack developer', 'full stack developer'), ('front-end developer', 'front-end developer'), ('back-end developer', 'back-end developer'), ('UI/UX designer', 'UI/UX designer'), ('database developer', 'database developer'), ('machine learning developer', 'machine learning developer')], max_length=200, null=True)),
                ('programming_languages', models.CharField(choices=[('python', 'python'), ('java', 'java'), ('matlab', 'matlab'), ('C++', 'C++'), ('django', 'django'), ('node js', 'node js'), ('HTML/CSS/JS', 'HTML/CSS/JS'), ('react', 'react'), ('angularJS', 'angularJS')], max_length=200, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField()),
                ('budjet', models.FloatField()),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.freelancer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.business')),
            ],
        ),
    ]
