# Generated by Django 4.1.7 on 2023-03-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_freelancer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
