# Generated by Django 4.1.7 on 2023-03-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_freelancer_profilepic_alter_freelancer_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='about',
            field=models.TextField(blank=True, default='Add your bio.'),
        ),
        migrations.AlterField(
            model_name='business',
            name='availableProjects',
            field=models.TextField(blank=True, default='Add your new projects.'),
        ),
        migrations.AlterField(
            model_name='business',
            name='completedProjects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='about',
            field=models.TextField(blank=True, default='Add your bio to get more attention.'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='certifications',
            field=models.TextField(blank=True, default='Add your certificates.'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='completedJobs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='skills',
            field=models.TextField(blank=True, default='Add your skills to get more attention.'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='wallet',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
