# Generated by Django 4.1.7 on 2023-03-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_business_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='name',
        ),
    ]
