# Generated by Django 4.1.7 on 2023-03-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='name',
            field=models.CharField(default='None_id', max_length=50),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='name',
            field=models.CharField(default='None_id', max_length=50),
        ),
    ]
