# Generated by Django 4.1.7 on 2023-03-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_business_name_freelancer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='availableProjects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
