# Generated by Django 4.1.7 on 2023-03-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_business_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
