# Generated by Django 4.1.7 on 2023-03-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_business_profilepic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='profilePic',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='profilePic',
        ),
        migrations.AddField(
            model_name='business',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
    ]
