# Generated by Django 4.1.7 on 2023-04-07 22:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_business_profilepic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='availableProjects',
        ),
        migrations.RemoveField(
            model_name='business',
            name='completedProjects',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('full stack developer', 'full stack developer'), ('front-end developer', 'front-end developer'), ('back-end developer', 'back-end developer'), ('UI/UX designer', 'UI/UX designer'), ('database developer', 'database developer'), ('machine learning developer', 'machine learning developer')], max_length=200, null=True)),
                ('programming_languages', models.CharField(choices=[('python', 'python'), ('java', 'java'), ('matlab', 'matlab'), ('C++', 'C++'), ('django', 'django'), ('node js', 'node js'), ('HTML/CSS/JS', 'HTML/CSS/JS'), ('react', 'react'), ('angularJS', 'angularJS')], max_length=200, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField()),
                ('budjet', models.FloatField()),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.freelancer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.business')),
            ],
        ),
    ]
