# Generated by Django 4.1.7 on 2023-04-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_business_availableprojects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='deadline',
            new_name='due_date',
        ),
    ]
