# Generated by Django 4.1.7 on 2023-04-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_rename_deadline_project_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='test',
            field=models.FloatField(default=2),
        ),
    ]
