# Generated by Django 4.1.7 on 2023-04-07 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_project_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='test',
        ),
    ]
