# Generated by Django 4.1.7 on 2023-04-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_project_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='completedJobs',
        ),
    ]
